### ISSUE TITLE
Stop supporting python3.8

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/movement#42]
[Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) introduced type hinting generics in standard collections via [PEP 585](https://peps.python.org/pep-0585/).
This allows us to directly use the usual Python collection types (eg `list`, `dict`) as type hints, instead of using `typing.List` and `typing.Dict`. Moreover, even though `typing` collections still work as type hints on newer Python versions, they are being deprecated.
The solution is to get rid of Python 3.8, the active support of which has already ended (with security support ending in ~1 year, see [endoflife.data](https://endoflife.date/python)).

**Comment by niksirbi** [comment]
Issue was raised by @lochhh while reviewing PR #33.

**Comment by lochhh** [comment]
We would still need ``typing.Optional`` and ``typing.Union`` in[ load_poses.py](https://github.com/neuroinformatics-unit/movement/blob/0eac6584c4a9a7614d7b285be49b10f01d700e1c/movement/io/load_poses.py#L3) with 3.9, since the ``|`` syntax is only supported [3.10](https://peps.python.org/pep-0604/) onwards.

**Comment by niksirbi** [comment]
@DhruvSkyy has kindly volunteered to have a shot at this one 🍾

**Comment by niksirbi** [comment]
closed via #54
