### ISSUE TITLE
Require pandas[hdf5] instead of vanilla pandas

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/movement#91]
@willGraham01 informed me that [if you install `pandas[hdf5]` instead of just "core" `pandas`](https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies), it comes with `pytables` and we shouldn't have to install it separately via `conda`.
We could potentially simplify our installation instructions down to a single `pip install movement`, but we have to see if CI still passes across OS and Python versions.

**Comment by niksirbi** [comment]
So this appears to work at first glance, see #104.
@willGraham01 could you help me understand a little bit better why this is working? I thought that the HDF5 libraries could not be distributed with pip, and that's why having say `h5py`/`pytables` as pip dependencies was not enough. What is different with `pandas[hdf5]`?
I'd appreciate it if you could lend me some of your hard-earned Python packaging wisdom.

**Comment by willGraham01** [comment]
My current understanding is that it looks like the latest version of the `h5py` package will attempt to fetch the HDF5 header files and compile them itself upon install, if they're not already on the system. You can see this in [their custom module build extension](https://github.com/h5py/h5py/blob/master/setup_build.py). `PyTables`, to the best of my knowledge, does not and requires the library to already be present on the system.

Thus, `pandas[hdf5]` fetches `h5py`, which in turn builds the appropriate hdf5 libraries / fetches the header files. In turn, `pandas[hdf5]` then uses `h5py` as the backend reader for HDF5 files, instead of `PyTables` (the default).

**Comment by niksirbi** [comment]
I see, thanks for the info. I'm happy with this being our solution for now.
